[{"ContainerToolsException.Message":"Для работы Средств Visual Studio для контейнеров необходимо запустить Docker перед сборкой, отладкой или запуском контейнерного проекта.  Дополнительные сведения см. на странице https://aka.ms/DockerToolsTroubleshooting.","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [22252] Failed to execute script docker-compose\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__16.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 289\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerComposeClient.<DownAsync>d__9.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:строка 111\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__34.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:строка 444\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:строка 16\r\n--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---\r\n   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   в Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() в D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:строка 84\r\nКод ошибки: DT1001\r\nСерьезность: Error\r\nКомандная строка: docker-compose  -f \"D:\\C#\\BusinessBanking\\docker-compose.yml\" -f \"D:\\C#\\BusinessBanking\\docker-compose.override.yml\" -f \"D:\\C#\\BusinessBanking\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose6034573879728661121 --ansi never kill\r\nКод завершения команды: -1\r\nВыходные данные команды: \r\nОшибка команды: Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\utils\\decorators.py\", line 46, in inner\r\n  File \"docker\\api\\client.py\", line 237, in _get\r\n  File \"requests\\sessions.py\", line 543, in get\r\n  File \"requests\\sessions.py\", line 530, in request\r\n  File \"requests\\sessions.py\", line 643, in send\r\n  File \"requests\\adapters.py\", line 439, in send\r\n  File \"urllib3\\connectionpool.py\", line 670, in urlopen\r\n  File \"urllib3\\connectionpool.py\", line 392, in _make_request\r\n  File \"http\\client.py\", line 1255, in request\r\n  File \"http\\client.py\", line 1301, in _send_request\r\n  File \"http\\client.py\", line 1250, in endheaders\r\n  File \"http\\client.py\", line 1010, in _send_output\r\n  File \"http\\client.py\", line 950, in send\r\n  File \"docker\\transport\\npipeconn.py\", line 32, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 23, in wrapped\r\n  File \"docker\\transport\\npipesocket.py\", line 72, in connect\r\n  File \"docker\\transport\\npipesocket.py\", line 52, in connect\r\npywintypes.error: (2, 'CreateFile', '═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.')\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', '═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы.')\r\n[22252] Failed to execute script docker-compose\r\n"}]